created_at: 2025-10-03 10:33:45.232620
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: Version de test
estimated_generation_time: null
excel_template_path: null
image_injections:
  A001:
  - background: false
    default_path: C:\Users\mosch\spirits_study\input\assets\background\secteur\Cuisine.png
    loop_dependent: false
    pattern: C:\Users\mosch\spirits_study\input\assets\background\secteur\{Background}.png
    position:
      left: 0.0
      top: 0.0
    size:
      max_height: 216.0
      max_width: 960.0
    type: secteur_image
loops:
- loop_id: Entreprise
  sheet_name: Boucles
  slides:
  - A001
name: BCE_INPI
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
