created_at: 2025-10-05 13:55:24.628625
created_by: null
data_source:
  connection_string: null
  required_tables: []
  type: excel
description: 'Analyse de la performance financière par entreprise

  '
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops:
- loop_id: A001
  sheet_name: Boucles
  slides:
  - A001
name: Fiche d'identité des entreprises
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
