created_at: 2025-10-01 15:59:41.496486
created_by: null
data_source:
  connection_string: null
  required_tables: []
  type: excel
description: Présentation automatisée BCE INSEE par entreprise et secteur
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops: []
name: INSEE_BCE
parameters:
- allowed_values: null
  balise_ppt: '[Entreprise]'
  default: null
  description: null
  name: Entreprise
  required: true
  type: string
- allowed_values: null
  balise_ppt: '[Background]'
  default: null
  description: null
  name: Background
  required: true
  type: string
ppt_template_path: null
slide_mappings: []
version: '1.0'
