created_at: 2025-10-04 16:07:25.780550
created_by: null
data_source:
  connection_string: null
  required_tables: []
  type: excel
description: Analyse des entreprises (id)
estimated_generation_time: null
excel_template_path: null
image_injections:
  A001:
  - background: false
    default_path: null
    loop_dependent: false
    pattern: C:\Users\mosch\spirits_study\input\assets\background\secteur\{Background}.png
    position:
      left: 0.0
      top: 0.0
    size:
      max_height: 216.0
      max_width: 690.0
    type: Back
loops:
- loop_id: Entreprise
  sheet_name: Charts_settings
  slides:
  - A001
name: BenchmarkV3
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
