created_at: 2025-10-01 15:32:11.230201
created_by: null
data_source:
  connection_string: null
  required_tables:
  - observations
  type: postgresql
description: Template de test
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops: []
name: test_template
parameters:
- allowed_values: null
  balise_ppt: '[Marque]'
  default: null
  description: null
  name: marque
  required: true
  type: string
ppt_template_path: null
slide_mappings: []
version: '1.0'
