created_at: 2025-10-03 20:44:07.622761
created_by: null
data_source:
  connection_string: null
  required_tables: []
  type: excel
description: Evaluation de la performance
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops: []
name: BenchmarkV2
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
