created_at: 2025-10-02 06:41:27.007325
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: Test
estimated_generation_time: null
excel_template_path: null
image_injections:
  A001:
  - background: true
    default_path: null
    pattern: C:\Users\mosch\spirits_study\input\assets\background\secteur\{Background}.png
    position:
      left: 0.0
      top: 0.0
    size:
      max_height: 216.0
      max_width: 960.0
    type: secteur_image
loops:
- loop_id: Entreprise
  sheet_name: Charts_settings
  slides:
  - A001
name: BCE_INSEE
parameters:
- allowed_values: null
  balise_ppt: '[Test]'
  default: null
  description: null
  name: Test
  required: true
  type: string
ppt_template_path: null
slide_mappings: []
version: '1.0'
