created_at: 2025-10-02 07:08:59.023194
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: ''
estimated_generation_time: null
excel_template_path: null
image_injections:
  A001:
  - background: false
    default_path: null
    pattern: C:\Users\mosch\Downloads\Logo noir.png
    position:
      left: 10.0
      top: 10.0
    size:
      max_height: 100.0
      max_width: 100.0
    type: Logo
loops:
- loop_id: Entreprise
  sheet_name: Charts_settings
  slides:
  - A001
name: TEST2
parameters:
- allowed_values: null
  balise_ppt: '[Entreprise]'
  default: null
  description: null
  name: Entreprise
  required: true
  type: string
ppt_template_path: null
slide_mappings: []
version: '1.0'
