created_at: 2025-10-03 12:02:44.760249
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: ''
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops: []
name: erffgzeb
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
