created_at: 2025-10-02 07:34:41.422073
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: ''
estimated_generation_time: null
excel_template_path: null
image_injections:
  A001:
  - background: true
    default_path: C:\Users\mosch\spirits_study\input\assets\background\secteur\Cuisine.png
    loop_dependent: true
    pattern: C:\Users\mosch\spirits_study\input\assets\background\secteur\{Background}.png
    position:
      left: 0.0
      top: 0.0
    size:
      max_height: 216.0
      max_width: 960.0
    type: Background
  - background: false
    default_path: null
    loop_dependent: false
    pattern: C:\Users\mosch\Downloads\Logo noir.png
    position:
      left: 0.0
      top: 0.0
    size:
      max_height: 216.0
      max_width: 960.0
    type: Logo
loops:
- loop_id: Entreprise
  sheet_name: Charts_settings
  slides:
  - A001
name: TESTV4
parameters:
- allowed_values: null
  balise_ppt: '[Entreprise]'
  default: null
  description: null
  name: Entreprise
  required: true
  type: string
- allowed_values: null
  balise_ppt: '[Background]'
  default: null
  description: null
  name: Background
  required: true
  type: string
ppt_template_path: null
slide_mappings: []
version: '1.0'
