created_at: 2025-10-03 10:41:58.337977
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: Fichier vide
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops: []
name: Test vide
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
