created_at: 2025-10-02 17:49:56.846761
created_by: null
data_source:
  connection_string: null
  required_tables:
  - Performance
  type: excel
description: ''
estimated_generation_time: null
excel_template_path: null
image_injections: {}
loops:
- loop_id: Concurrents
  sheet_name: Boucles
  slides:
  - A106
- loop_id: Produits
  sheet_name: Boucles
  slides:
  - B010
  - C003
  - C017
  - C018
  - D005
  - D007
  - D008
- loop_id: Produit_cct
  sheet_name: Boucles
  slides:
  - C007
name: SAMMPO
parameters:
- allowed_values: null
  balise_ppt: '[XXX]'
  default: null
  description: null
  name: X
  required: true
  type: string
ppt_template_path: null
slide_mappings:
- excel_range: P3:U7
  has_header: false
  sheet_name: Table
  slide_id: A104
- excel_range: B3:G11
  has_header: true
  sheet_name: Table
  slide_id: A105
- excel_range: AE3:AH11
  has_header: true
  sheet_name: Table
  slide_id: A106
- excel_range: X3:AA12
  has_header: true
  sheet_name: Table
  slide_id: A003
- excel_range: AV3:AZ10
  has_header: true
  sheet_name: Table
  slide_id: B003
- excel_range: AL3:AQ12
  has_header: true
  sheet_name: Table
  slide_id: B004
- excel_range: BD3:BG12
  has_header: true
  sheet_name: Table
  slide_id: B009
- excel_range: BK2:BU5
  has_header: false
  sheet_name: Table
  slide_id: C003
- excel_range: BX3:CA12
  has_header: true
  sheet_name: Table
  slide_id: C014
- excel_range: CI2:CV16
  has_header: false
  sheet_name: Table
  slide_id: D004
- excel_range: CJ2:CU2
  has_header: false
  sheet_name: Table
  slide_id: D002
version: '1.0'
