created_at: 2025-10-04 14:57:14.155974
created_by: null
data_source:
  connection_string: null
  required_tables: []
  type: excel
description: Fiche d'identité par entreprise avec la performance financière (CA, structure
  de la marge, évolution de la marge, etc.)
estimated_generation_time: null
excel_template_path: null
image_injections:
  A001:
  - background: false
    default_path: null
    loop_dependent: false
    pattern: C:\Users\mosch\spirits_study\input\assets\background\secteur\{Background}.png
    position:
      left: 0.0
      top: 0.0
    size:
      max_height: 216.0
      max_width: 960.0
    type: Background
loops:
- loop_id: Entreprise
  sheet_name: Charts_settings
  slides:
  - A001
name: Benchmark marché
parameters: []
ppt_template_path: null
slide_mappings: []
version: '1.0'
